### ISSUE TITLE
Enhancement: swagger?

### ISSUE THREAD

**Issue by inktrap** [sloth-ci/sloth-ci#5]
Wouldn't it be great to have swagger-ui as an extension and some openapi spec?

**Comment by inktrap** [comment]
Looks like this is the URL structure …

```
http://mydomain.com:8080/?action=ACTION&listen_point=LISTEN_POINT
```

A ``LISTEN_POINT`` is a kind of arbitrary name, like ``test`` and ACTION is f.e. one of:

```
bind
history
info
logs
remove
trigger
```

So one would have to document the actions per ``LISTEN_POINT``.

The listen points and their actions are dynamically created via ``bed.py``, so one would have to inspect ``Bed()`` instances.

It seems easier to write a [Spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md)  for a schema like [gitea's](https://try.gitea.io/api/swagger#/repository) which lists the actions first, then the variable part.

**Comment by inktrap** [comment]
To quote the section ["Query String in Paths"](https://swagger.io/docs/specification/describing-parameters/)

> Query string parameters must not be included in paths. They should be defined as query parameters instead.
> 
> Incorrect:
> 
> ```
> paths:
>   /users?role={role}:
> ```
> 
> Correct:
> 
> ```
> paths:
>   /users:
>     get:
>       parameters:
>         - in: query
>           name: role
>           schema:
>             type: string
>             enum: [user, poweruser, admin]
>           required: true
> ```
> 
> This also means that it is impossible to have multiple paths that differ only in query string, such as:
> 
> ```
> GET /users?firstName=value&lastName=value
> GET /users?role=value
> ```
> 
> This is because OpenAPI considers a unique operation as a combination of a path and the HTTP method, and additional parameters do not make the operation unique. Instead, you should use unique paths such as:
> 
> ```
> GET /users/findByName?firstName=value&lastName=value
> GET /users/findByRole?role=value
> ```

This means that something like this won't capture the sloth-ci api … 

```
openapi: 3.0.0
info:
  version: 1.0.0
  title: Sloth-CI API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /
    get:
      description: Returns a list of stuff
      parameters:
        - name: listen_point
          in: query
          description: Specifies the listen point to act upon
          schema:
            type: string
        - name: action
          in: query
          schema:
            type: string
            enum:
              - bind
              - history
              - info
              - logs
              - remove
              - trigger
          required: true
          description: The action to perform
      responses:
        '200':
```

**Comment by inktrap** [comment]
One solution would be to rewrite the URL to something like:

```
http://mydomain.com:8080/action/$ACTION/listen_point/$LISTEN_POINT
```

**Comment by moigagoo** [comment]
Sloth's API is not RESTful, and Swagger is for REST only.

**Comment by inktrap** [comment]
If you don't want to consider a rewrite you can close this.
